---
- hosts: all
  vars:
    message: Hello From Vars CHANGED
    another_variable: Another variable
  become: yes
  tasks:
    - name: Write file
      template:
        src: ./test.j2
        dest: /etc/test.txt
        mode: "0644"
